# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
