# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161126_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='private',
            field=models.NullBooleanField(),
        ),
    ]
